### ISSUE TITLE
Trying to update an SLO that was applied with empty alerting definition crashes

### ISSUE THREAD

**Issue by ellisda** [grafana/terraform-provider-grafana#1067]
### Terraform Version
* Terraform: 1.5.4
* Terraform Grafana Provider: 2.3.3

### Affected Resource(s)
Please list the resources as a list, for example:
* slo

### Terraform Configuration Files
I'm using terraform's json syntax. This is used to create, then the panic below happens on an attempt to modify this. To modify, change `le=\"0.1\"` to `le=\"0.01\"` and try to apply
```
{
  "resource": {
    "grafana_slo": {
      "slos_test": {
        "name": "my SLO",
        "description": "",
        "query": {
          "type": "ratio",
          "ratio": {
            "success_metric": "metric{status_code!~\"5..\",le=\"0.1\"}",
            "total_metric": "metric{status_code!~\"5..\"}",
            "group_by_labels": [ "cluster", "namespace"]
          }
        },
        "objectives": [
          { "value": 0.995, "window": "28d" }
        ],
        "label": [
          { "key": "team", "value": "gops_slos" }
        ],
        "alerting": {
        }
      }
    }
  }
}
```

### Panic Output
```
Acquiring state lock. This may take a few moments...
grafana_slo.slos_test: Modifying... [id=pty05kl89j8wemnf0f2oj]

Error: Plugin did not respond

  with grafana_slo.slos_test_stack_status_service_success,
  on stack-state-service.tf.json line 32, in resource.grafana_slo.slos_test:
  32:       }

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-grafana_v2.3.3 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 43 [running]:
github.com/grafana/terraform-provider-grafana/internal/resources/slo.packAlertMetadata({0x188a9a8?, 0xc0001aa1b0?, 0x1004494?})
	github.com/grafana/terraform-provider-grafana/internal/resources/slo/resource_slo.go:460 +0x5f3
github.com/grafana/terraform-provider-grafana/internal/resources/slo.packAlerting(0x188a9a8?)
	github.com/grafana/terraform-provider-grafana/internal/resources/slo/resource_slo.go:444 +0x517
github.com/grafana/terraform-provider-grafana/internal/resources/slo.packSloResource(0xc000054c80)
	github.com/grafana/terraform-provider-grafana/internal/resources/slo/resource_slo.go:346 +0x645
github.com/grafana/terraform-provider-grafana/internal/resources/slo.resourceSloUpdate({0x11867a8, 0xc00058dd40}, 0xc000054c80, {0xe56fa0?, 0xc00066aff0?})
	github.com/grafana/terraform-provider-grafana/internal/resources/slo/resource_slo.go:271 +0x245
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0002d0fc0, {0x11867e0, 0xc0006a2f60}, 0xd?, {0xe56fa0, 0xc00066aff0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:812 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002d0fc0, {0x11867e0, 0xc0006a2f60}, 0xc0003d40d0, 0xc000054a00, {0xe56fa0, 0xc00066aff0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000477e30, {0x11867e0?, 0xc0006a2e40?}, 0xc000788410)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00036b2c0, {0x11867e0?, 0xc0006a2630?}, 0xc00027b960)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xfc85c0?, 0xc00036b2c0}, {0x11867e0, 0xc0006a2630}, 0xc00027b8f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00001c1e0, {0x118ac78, 0xc0006829c0}, 0xc0007805a0, 0xc000480c30, 0x1840a58, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc00001c1e0, {0x118ac78, 0xc0006829c0}, 0xc0007805a0, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-grafana_v2.3.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

exit status 1


```

### Expected Behavior
I should have been able to make a minor modification to the slo that was previously applied successfully

### Actual Behavior
Despite the initial apply working, when I tried to modify the SLO, it crashed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with file from above (note: that the "alerting" sub object is empty, this will be a problem later
2. verify success apply
3. make modification to .tf.json, ex:  `le=\"0.1\"` to `le=\"0.01\"` and try to apply
4. verify tf panic resulting from empty alerting body

**Comment by dsolsona** [comment]
I'm also seeing this issue with terraform 1.5.3 and the latest provider version 2.6.1

Perhaps the code is missing some safety checks when fetching  the fastburn and slowburn  in https://github.com/grafana/terraform-provider-grafana/blob/master/internal/resources/slo/resource_slo.go#L497 and causes the panic here https://github.com/grafana/terraform-provider-grafana/tree/master/internal/resources/slo#L513

If you go and define the fastburn and slowburn as empty in terraform like so

```
resource "grafana_slo" "main" {
  ...
  ...

  fastburn {}
  slowburn {}
}
```

Then the plan doesn't throw any warning and the apply will fail  with

```

Stack trace from the terraform-provider-grafana_v2.6.1 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}
```
