### ISSUE TITLE
[Bug]: grafana_dashboard pass map atrribute to jsonencode provider crash

### ISSUE THREAD

**Issue by GunFood** [grafana/terraform-provider-grafana#1877]
### Terraform Version

1.8.4

### Terraform Grafana Provider Version

3.10.0

### Grafana Version

11.3.0

### Affected Resource(s)

```
Stack trace from the terraform-provider-grafana_v3.10.0 plugin:
  
  **panic: interface conversion: interface {} is []interface {}, not map[string]interface {}**
  
  goroutine 189 [running]:
  github.com/grafana/terraform-provider-grafana/v3/internal/resources/grafana.NormalizeDashboardConfigJSON({0x1764360?, 0xc000c55ac0?})
        github.com/grafana/terraform-provider-grafana/v3/internal/resources/grafana/resource_dashboard.go:283 +0x359
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc000ef6b60?, {0x1b375ce, 0xb}, 0xc0004a5540, 0xc000ef6c40, {0x1e51170, 0xc0006fc500}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:1549 +0xf8
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc00070b5c0, {0x1e49dd8, 0xc000c419e0}, {0x1b375ce, 0xb}, 0xc0004a5540, 0xc0006fc380, {0x1e51170, 0xc0006fc500}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:1128 +0x165
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00070b5c0, {0x1e49dd8, 0xc000c419e0}, 0xc0004d3110, 0xc000c522d0, 0x0, {0x180e1c0, 0xc000896f00}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:678 +0x332
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x1e4a6d0?, {0x1e49dd8?, 0xc000c419e0?}, 0xc0004d3110, 0xc000c41a10?, {0x180e1c0?, 0xc000896f00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:990 +0xdb
  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc000686498, {0x1e49dd8?, 0xc000c418f0?}, 0xc000c52000)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:858 +0xbe8
  github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc000143260, {0x1e49dd8?, 0xc000c41620?}, 0xc000c52000)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc000638000, {0x1e49dd8?, 0xc000c40e10?}, 0xc0006fc100)
        github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:825 +0x3f0
  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x1ac42a0, 0xc000638000}, {0x1e49dd8, 0xc000c40e10}, 0xc0006fc080, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:527 +0x1a6
  google.golang.org/grpc.(*Server).processUnaryRPC(0xc000519000, {0x1e49dd8, 0xc000c40d80}, {0x1e53940, 0xc0004d84e0}, 0xc000c4aa20, 0xc0004b4b70, 0x2ea01a0, 0x0)
        google.golang.org/grpc@v1.66.2/server.go:1394 +0xe49
  google.golang.org/grpc.(*Server).handleStream(0xc000519000, {0x1e53940, 0xc0004d84e0}, 0xc000c4aa20)
        google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
  google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.2/server.go:1029 +0x8b
  created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 30
        google.golang.org/grpc@v1.66.2/server.go:1040 +0x125
  
  Error: The terraform-provider-grafana_v3.10.0 plugin crashed!
```

### Terraform Configuration Files

Source not working:
```
terraform {
  required_providers {
    grafana = {
      source = "hashicorp/grafana"
      version = "3.10.0"
    }
  }
}

resource "grafana_dashboard" playground-dashboard" {
  provider = grafana
  folder = grafana_folder.dashboard_folder.uid
  config_json = templatefile(
    "${path.module}/dashboard_template.json", 
    {
      btds = "datasource"
      cmkdstype = "tribe-29-checkmk-datasource"
      panels = jsonencode(
        [
          {
            gridPos = {
              h = 4,
              w = 8,
              x = 0,
              y = 0
            }
            libraryPanel = {
              name = grafana_library_panel.playground-cpu-panel.name
              uid  = grafana_library_panel.playground-cpu-panel.uid
            }
            title = "CPU Panel"
          },
          {
            gridPos = {
              h = 8,
              w = 12,
              x = 0,
              y = 10
            }
            libraryPanel = {
              name = grafana_library_panel.playground-filesystem-root-panel.name
              uid  = grafana_library_panel.playground-filesystem-root-panel.uid
            }
            title = "filesystem / $server"
          }
        ]
      )
    }
  )
```

Source working (only one panel):
```
terraform {
  required_providers {
    grafana = {
      source = "hashicorp/grafana"
      version = "3.10.0"
    }
  }
}

resource "grafana_dashboard" "playground-dashboard" {
  provider = grafana
  folder = grafana_folder.dashboard_folder.uid
  config_json = templatefile(
    "${path.module}/dashboard_template.json", 
    {
      btds = "datasource"
      cmkdstype = "tribe-29-checkmk-datasource"
      panels = jsonencode(
          {
            gridPos = {
              h = 8,
              w = 12,
              x = 0,
              y = 10
            }
            libraryPanel = {
              name = grafana_library_panel.playground-filesystem-root-panel.name
              uid  = grafana_library_panel.playground-filesystem-root-panel.uid
            }
            title = "filesystem / $server"
          }
      )
    }
  )
```

the JSON file dahsboard_templete.json:
```
{
    "title": "Test Dashboard",
    "annotations": {
    "list": [ ]
    },
    "panels": [${panels}],
    "templating": {
      "list": [
        {
            "name": "server",
            "type": "query",
            "label": "Select Server",
            "current": {
                "selected": false,
                "text": "one-server.local",
                "value": "one-server.local"
            },
            "datasource": {
                "type": "${cmkdstype}",
                "uid": "${btds}"
                },
            "definition": "host: {\"host_labels\":[\"sw/dbms/mariadb:yes\"]}",
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "options": [],
            "query": {
                "filter": {
                "host_labels": [
                    "sw/dbms/mariadb:yes"
                ]
                },
                "objectType": "host"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0
        }
      ]
    }
  }
```

### Expected Behavior

We would like to create dashboards, using multiple library panels. Adding more than one panel and converting the jsonencode to a map, causes the provider to crash.

**Comment by diseku** [comment]
we're experiencing the same issue. assuming related to the recent grafana 11.3.0 release

**Comment by GunFood** [comment]
We had the same issue with Grafana 11.2.0 also. Did it work for you in an older version?

**Comment by Duologic** [comment]
The template file wraps the variable `${panels}` in `[]`:    `"panels": [${panels}]`

So if you do `jsonencode( [ { /* panel */ } ] )`, then this would result in `"panels": [[ { /* panel */ } ]]`, wrapping the panel(s) into two `[[]]`, right?

**Comment by GunFood** [comment]
hmm. maybe. Will check.
In the meantime, we worked around the issue, by creating the whole dashboard with jsonencode end do not use the templatefile function.

```
resource "grafana_dashboard" "playground-dashboard" {
  provider = grafana
  config_json = jsonencode(
    {
      title = "0-Overview"
      panels = [
        {
          gridPos = {
            h = 4
            w = 4
            x = 0
            y = 0
          },
          libraryPanel = {
            name = module.panel.ampel_panel_name
            uid  = module.panel.ampel_panel_uid
          },
          title = ""
        },
        {
          gridPos = {
            h = 4
            w = 4
            x = 5
            y = 0
          },
          libraryPanel = {
            name = module.panel.ampel_panel2_name
            uid  = module.panel.ampel_panel2_uid
          },
          title = ""
        }
      ]
    }
  )
}
```

**Comment by Duologic** [comment]
I'm closing this for now as it doesn't seem to be caused by the provider.
