### ISSUE TITLE
SIGSEV when invalid profile used

### ISSUE THREAD

**Issue by sophie-warner-annalise-ai** [grafana/terraform-provider-grafana#1925]
### Terraform Version

OpenTofu v1.8.5

### Terraform Grafana Provider Version

v3.13.1

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "productio"
  region  = "ap-southeast-2"

  default_tags {
    tags = local.tags
  }
}
```

### Actual Behavior

```
│ Error: failed to get shared config profile, productio
│
│   with provider["registry.opentofu.org/hashicorp/aws"],
│   on provider.tf line 36, in provider "aws":
│   36: provider "aws" {
│
╵

Stack trace from the terraform-provider-grafana_v3.13.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x1035eb478]

goroutine 122 [running]:
github.com/grafana/terraform-provider-grafana/v3/internal/resources/oncall.(*userDataSource).Read(0x14000090a10, {0x103e57778, 0x14000d18450}, {{{{0x103e60018, 0x14000d18ae0}, {0x103b1e6e0, 0x14000d18a50}}, {0x103e63f08, 0x14000908b40}}, {{{0x0, ...}, ...}, ...}, ...}, ...)
	github.com/grafana/terraform-provider-grafana/v3/internal/resources/oncall/data_source_user.go:60 +0x148
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0x140005701e0, {0x103e57778, 0x14000d18450}, 0x14000908740, 0x140000634d0)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/fwserver/server_readdatasource.go:103 +0x638
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0x140005701e0, {0x103e57778?, 0x14000d182d0?}, 0x14000d18390)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/proto6server/server_readdatasource.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-mux/tf6to5server.v6tov5Server.ReadDataSource({{0x103e693b0?, 0x140005701e0?}}, {0x103e57778?, 0x14000d182d0?}, 0x14000e8dda0?)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf6to5server/tf6to5server.go:165 +0x254
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0x1400012b570, {0x103e57778?, 0x14000e8de00?}, 0x14000e8dda0)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0x1400071b040, {0x103e57778?, 0x14000c8f1a0?}, 0x14000c968c0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:688 +0x1cc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x103dc6ba0, 0x1400071b040}, {0x103e57778, 0x14000c8f1a0}, 0x14000a1a100, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:599 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400015b200, {0x103e57778, 0x14000c8f110}, {0x103e61c40, 0x140008fc000}, 0x14000cc2b40, 0x140005f5e90, 0x104e9df60, 0x0)
	google.golang.org/grpc@v1.67.1/server.go:1394 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x1400015b200, {0x103e61c40, 0x140008fc000}, 0x14000cc2b40)
	google.golang.org/grpc@v1.67.1/server.go:1805 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.67.1/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.67.1/server.go:1040 +0x13c

Error: The terraform-provider-grafana_v3.13.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

Weirdly having an invalid AWS provider caused the grafana pludin to SIGSEV. Fixing this removed the issue.

**Comment by Duologic** [comment]
The stacktrace suggest something goes wrong in the GRPC server, I'd suggest reporting this in the OpenTofu project, seems unrelated to the Grafana provider as it doesn't crash without the AWS provider block.
