### ISSUE TITLE
Dashboard resource not working with Grafana v8

### ISSUE THREAD

**Issue by pabloajz** [grafana/terraform-provider-grafana#212]
### Terraform Version
* Terraform: 0.14.10
* Terraform Grafana Provider: 1.11.0
* Grafana: 8.0.0

### Affected Resource(s)
* grafana_dashboard

### Terraform Configuration Files
```hcl

```

### Expected Behavior
Existing dashboards should keep working after migrating from Grafana v7 to v8
New dashboards should be created in Grafana v8

### Actual Behavior
What actually happened?

Grafana 8 has removed from the API the slug id > https://github.com/grafana/grafana/pull/35104
So when upgrading to Grafana v8 this provider basically stops working.

This is blocking upgrading Grafana to v8

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

For existing resources > After upgrading Grafana from version 7 to 8, on first apply it shows a version mismatch and try to recreate the dashboard,

```Error: status: 412, body: {"message":"The dashboard has been changed by someone else","status":"version-mismatch"}```

then it fails because the dashboard already exists with the same name.

```Error: status: 412, body: {"message":"A dashboard with the same name in the folder already exists","status":"name-exists"}```

For new resources it creates the dashboard but it fails to store the resource into the terraform state, I guess because the API is not accepting/returning the slug anymore

```
Error: Provider produced inconsistent result after apply

When applying changes to module.k8s_grafana.grafana_dashboard.metrics[0],
provider "registry.terraform.io/grafana/grafana" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

As solution we had to rollback Grafana to v7 and remove manually affected dashboards , recreating them again with terraform

### Important Factoids
none

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/grafana/terraform-provider-grafana/issues/95
- https://github.com/grafana/grafana/pull/35104

**Comment by gfrankel97** [comment]
Seeing this behavior as well. Terraform Grafana provider is rendered unusable upon upgrading to Grafana v8.0.1.

**Comment by moogly81** [comment]
We're having the same issue. The provider is broken. 

note:  dashboard creation by terraform is actually successful. But the importation in the terraform state fails. 
As a result, terraform always wants to recreate all the dashboards at plan stage, and fails at apply.
However, you end up with a working grafana, with dashboards imported.

**Comment by harpunius** [comment]
We had to roll back to grafana v7 and re-import all dashboards as they had been deleted from the state (while still existing in grafana).

**Comment by MRinalducci** [comment]
Same issue here.

**Comment by PavelPikat** [comment]
@julienduchesne Seems like there's PR ready to be merged, can we have this fixed please?

**Comment by BWalti** [comment]
I'd say this is the mentioned PR: https://github.com/grafana/terraform-provider-grafana/pull/217

**Comment by mogopz** [comment]
Thanks for fixing @trotttrotttrott - do you know when there'll be a new release with v8 support?

**Comment by trotttrotttrott** [comment]
@mogggggg planning to release as soon as I can get ~~https://github.com/grafana/terraform-provider-grafana/issues/223~~ https://github.com/grafana/terraform-provider-grafana/pull/224 approved and merged. It resolves a bug I introduced in https://github.com/grafana/terraform-provider-grafana/pull/217 around managing `uid`. Hoping that'll be today.

**Comment by Obsecurus** [comment]
Thanks for cranking this out @trotttrotttrott! will you be cutting a release for this?

**Comment by trotttrotttrott** [comment]
v1.12.0 has been released with the fix in place! Please reopen or open new issues if you run into trouble.

**Comment by justinTM** [comment]
got some NASTY error after upgrading versions.tf grafana provider plugin to 1.12 and then running
```shell
terraform init -upgrade
```

the error refers to failed unmarshalling of JSON. however, we checked the JSON and it is exactly the same as a known-good (successful) plan+apply. goes away after downgrading back to 1.10, but of course 1.10 has its own issues.

here is the error output from terraform. can email TRACE json (terraform 1.15) if desired.

thanks in advance.

```shell
terragrunt plan
WARN[0000] No double-slash (//) found in source URL <>. Relative paths in downloaded Terraform code may not work. 
grafana_folder.collection: Refreshing state... [id=66]
local_file.foo["placeholder.json"]: Refreshing state... [id=c348e4ebb29c6405bf4e6490b0163c862944758b]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│   with grafana_dashboard.metrics["dashboard1/cluster-resources.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard2/service-dashboard.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard3/dashboard3-clusters.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard3/dashboard3-topics.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["generic.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard4/dashboard4-overview.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard5/dashboard5.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard1/dashboard1.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard6/dashboard6.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with grafana_dashboard.metrics["dashboard3/dashboard3.json"],
│   on dashboards.tf line 32, in resource "grafana_dashboard" "metrics":
│   32: resource "grafana_dashboard" "metrics" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-grafana_v1.12.0 plugin:

panic: Attempted to unmarshal invalid JSON. This unexpectedly got past schema validation.

goroutine 78 [running]:
github.com/grafana/terraform-provider-grafana/grafana.unmarshalDashboardConfigJSON(0x197e2a6, 0x24, 0x1843c80)
        github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:268 +0x106
github.com/grafana/terraform-provider-grafana/grafana.normalizeDashboardConfigJSON(0x1843c80, 0xc000714fa0, 0xb, 0x0)
        github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:299 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc0002e0990, 0x19698d1, 0xb, 0xc0002f9680, 0xc000139508, 0x1a72d98, 0xc000596900, 0x203000, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:1375 +0x6e3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc0002e0990, 0x19698d1, 0xb, 0xc0002f9680, 0xc000684540, 0x1a72d98, 0xc000596900, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:957 +0x4e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0002e0990, 0x1a6f138, 0xc0006dcb80, 0xc00021a150, 0xc000177ef0, 0x0, 0x181c760, 0xc00021d260, 0x1f28c00, 0x1843c80, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:522 +0x219
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc00020eb60, 0x1a6f138, 0xc0006dcb80, 0xc00021a150, 0xc000177ef0, 0x181c760, 0xc00021d260, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:506 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00018f410, 0x1a6f138, 0xc0006dcb80, 0xc0001a7860, 0xc0006dcb80, 0x1929940, 0xc000177900)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:693 +0x7c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc0004986a0, 0x1a6f1e0, 0xc0006dcb80, 0xc00021a000, 0xc0004986a0, 0xc000177980, 0xc000529ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x1929940, 0xc0004986a0, 0x1a6f1e0, 0xc000177980, 0xc0000bf5c0, 0x0, 0x1a6f1e0, 0xc000177980, 0xc0000fe240, 0xbb)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002dea80, 0x1a76998, 0xc0001a1c80, 0xc000179d40, 0xc00010c630, 0x1eeaec8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002dea80, 0x1a76998, 0xc0001a1c80, 0xc000179d40, 0x0)
        google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b01e0, 0xc0002dea80, 0x1a76998, 0xc0001a1c80, 0xc000179d40)
        google.golang.org/grpc@v1.37.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

Error: The terraform-provider-grafana_v1.12.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0002] 1 error occurred:
        * exit status 1
```

**Comment by francardoso93** [comment]
For someone that might find this through google. In my case the issues were in that part of the code:

```
"libraryPanel": {
          "name": "S3 Fetches Duration",
          "uid": "Kh_QhKYnk"
        },
 "type": "Name: \"S3 Fetches Duration\", UID: \"Kh_QhKYnk\""
```

Everything worked when I changed to:
```
"title": "S3 Fetches Duration",
"type": "timeseries"`
```
