### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing / rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by flokli** [grafana/terraform-provider-grafana#249]
### Terraform Version
* Terraform: v0.12.31
* Terraform Grafana Provider: v1.12.0
* Grafana: N/A

### Affected Resource(s)
All

### Expected Behavior

In some cases, during the plan phase, I see the following output too:

```
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: panic: Attempted to unmarshal invalid JSON. This unexpectedly got past schema validation.
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: goroutine 24 [running]:
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/grafana/terraform-provider-grafana/grafana.unmarshalDashboardConfigJSON(0xd83db5, 0x24, 0xc496e0)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:268 +0x106
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/grafana/terraform-provider-grafana/grafana.normalizeDashboardConfigJSON(0xc496e0, 0xc0002e4f40, 0xb, 0x0)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:299 +0x145
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc0001164b0, 0xd6f1ce, 0xb, 0xc000280140, 0xc0004e5508, 0xe77e98, 0xc00030a400, 0x203000, 0x0, 0x0)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:1375 +0x6e3
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc0001164b0, 0xd6f1ce, 0xb, 0xc000280140, 0xc000804340, 0xe77e98, 0xc00030a400, 0x0, 0x0, 0x0)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:957 +0x4e8
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0001164b0, 0xe74358, 0xc0001fec80, 0xc00013c310, 0xc0002e9140, 0x0, 0xc21e00, 0xc0002aab00, 0x132e400, 0xc496e0, ...)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:522 +0x219
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc00017e380, 0xe74358, 0xc0001fec80, 0xc00013c310, 0xc0002e9140, 0xc21e00, 0xc0002aab00, 0x0, 0x0, 0x0)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:506 +0xa5
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00010e078, 0xe74358, 0xc0001fec80, 0xc0007ae370, 0xc0001fec80, 0xd2efc0, 0xc0002e8600)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:693 +0x7c5
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc00049d080, 0xe74400, 0xc0001fec80, 0xc00013c1c0, 0xc00049d080, 0xc0002e8690, 0xc0000a5ba0)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0xb5
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0xd2efc0, 0xc00049d080, 0xe74400, 0xc0002e8690, 0xc0000733e0, 0x0, 0xe74400, 0xc0002e8690, 0xc00005e180, 0xb2)
2021-07-26T19:00:04.691+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002768c0, 0xe7ba38, 0xc00058a600, 0xc000168a20, 0xc00031c5d0, 0x12f00a8, 0x0, 0x0, 0x0)
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: google.golang.org/grpc.(*Server).handleStream(0xc0002768c0, 0xe7ba38, 0xc00058a600, 0xc000168a20, 0x0)
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000425e0, 0xc0002768c0, 0xe7ba38, 0xc00058a600, 0xc000168a20)
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	google.golang.org/grpc@v1.37.0/server.go:878 +0xab
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-07-26T19:00:04.692+0200 [DEBUG] plugin.terraform-provider-grafana_v1.12.0: 	google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
2021/07/26 19:00:04 [ERROR] module.grafana_dashboards: eval: *terraform.EvalReadState, err: rpc error: code = Unavailable desc = transport is closing
2021/07/26 19:00:04 [ERROR] module.grafana_dashboards: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021-07-26T19:00:04.694+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/07/26 19:00:04 [TRACE] [walkRefresh] Exiting eval tree: module.grafana_dashboards.grafana_dashboard.brossa
2021/07/26 19:00:04 [TRACE] vertex "module.grafana_dashboards.grafana_dashboard.brossa": visit complete
2021/07/26 19:00:04 [ERROR] module.grafana_dashboards: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2021-07-26T19:00:04.694+0200 [DEBUG] plugin: plugin process exited: path=/nix/store/jk0sm06s4i4qhl0h2kpzafdgy76kd7fb-terraform-0.12.31/plugins/terraform-provider-grafana_v1.12.0 pid=342882 error="exit status 2"
2021/07/26 19:00:04 [ERROR] module.grafana_dashboards: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
```

This will bubble up and cause a `tf apply` to fail:

```
Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Canceled desc = context canceled
```

**Comment by flokli** [comment]
Seems to be a dup of https://github.com/grafana/terraform-provider-grafana/issues/238.

**Comment by akshaychopra5207** [comment]
HI @flokli 

I am still getting the same error after I have upgraded the version to 1.13.3

**Versions I am using**
Terraform v0.13.4
+ provider digitalplatform.local/maf/digitalplatform v1.0.1
+ provider registry.terraform.io/grafana/grafana v1.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
+ provider registry.terraform.io/hashicorp/http v1.2.0

**Error during plan**
```
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: panic: Attempted to unmarshal invalid JSON. This unexpectedly got past schema validation.
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: 
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: goroutine 40 [running]:
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/grafana/terraform-provider-grafana/grafana.unmarshalDashboardConfigJSON(0x19ba146, 0x24, 0x18747e0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:268 +0x106
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/grafana/terraform-provider-grafana/grafana.normalizeDashboardConfigJSON(0x18747e0, 0xc0000aebd0, 0xb, 0x18747e0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:299 +0x145
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc0000aa870, 0x19a4dad, 0xb, 0xc0003b6280, 0xc000375508, 0x1ab41d8, 0xc000175b80, 0x203000, 0x0, 0x0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:1375 +0x6e3
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc0000aa870, 0x19a4dad, 0xb, 0xc0003b6280, 0xc00089a780, 0x1ab41d8, 0xc000175b80, 0x0, 0x0, 0x0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:957 +0x4e8
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0000aa870, 0x1ab05b8, 0xc0002e42c0, 0xc0001b2bd0, 0xc000302d80, 0x0, 0x184bce0, 0xc0002c6dc0, 0x1f8ff00, 0x18747e0, ...)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:522 +0x219
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc0003b4380, 0x1ab05b8, 0xc0002e42c0, 0xc0001b2bd0, 0xc000302d80, 0x184bce0, 0xc0002c6dc0, 0x0, 0x0, 0x0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:506 +0xa5
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0000da078, 0x1ab05b8, 0xc0002e42c0, 0xc0002d6b90, 0xc0002e42c0, 0x1963d60, 0xc0002dab00)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:693 +0x7c5
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc00082c580, 0x1ab0660, 0xc0002e42c0, 0xc0001b29a0, 0xc00082c580, 0xc0002dab40, 0xc000525ba0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0xb5
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x1963d60, 0xc00082c580, 0x1ab0660, 0xc0002dab40, 0xc0000a8840, 0x0, 0x1ab0660, 0xc0002dab40, 0xc000526000, 0xa3b4)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027c8c0, 0x1ab7f58, 0xc000135500, 0xc00022c360, 0xc000302690, 0x1f51088, 0x0, 0x0, 0x0)
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: google.golang.org/grpc.(*Server).handleStream(0xc00027c8c0, 0x1ab7f58, 0xc000135500, 0xc00022c360, 0x0)
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b6210, 0xc00027c8c0, 0x1ab7f58, 0xc000135500, 0xc00022c360)
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:934 +0xab
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
2021-08-04T13:15:35.981+0400 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-08-04T13:15:35.982+0400 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/grafana/grafana/1.13.3/darwin_amd64/terraform-provider-grafana_v1.13.3 pid=90788 error="exit status 2"
2021/08/04 13:15:35 [ERROR] eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2021/08/04 13:15:35 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
```
